import { type NextPage } from "next";
import Head from "next/head";
import { trpc } from "../utils/trpc";
import { WorkoutCard } from '../components/workoutCard';

const AllWorkouts: NextPage = () => {
  const { data: workouts, isLoading } = trpc.workout.getAllWorkouts.useQuery();

  if (isLoading) return <div>Fetching messages...</div>;

  return (
    <>
      <Head>
        <title>All Workouts</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        <div className="container flex flex-col items-center gap-12 px-4 py-16 ">
          <h4 className="text-2xl font-extrabold tracking-tight text-white sm:text-[3rem]">
            All Workouts
          </h4>
          <div className="grid grid-cols-1 gap-4 sm:grid-cols-2 md:gap-8">
            {workouts?.map((workout, index) => {
              return (
                <WorkoutCard key={workout.title} {...workout} />
              );
            })}
          </div>
        </div>
      </main>
    </>
  );
};

export default AllWorkouts;
