import Head from "next/head";

export const PageHead = ({ title }: { title: string }) => (
  <Head>
    <title>{title}</title>
    <meta name="description" content="Generated by create-t3-app" />
    <meta name="theme-color" content="#RRGGBB"></meta>
    <link rel="icon" href="/favicon.ico" />
    <link rel="manifest" href="/manifest.json" />
  </Head>
);
